.nh
.TH "anvil" "1" "Mar 2024" "" ""

.SH NAME
.PP
anvil-component - Prints component configs


.SH SYNOPSIS
.PP
\fBanvil component [flags]\fP


.SH DESCRIPTION
.PP
Prints component configs


.SH OPTIONS
.PP
\fB-c\fP, \fB--cache\fP=""
	repo cache directory

.PP
\fB-n\fP, \fB--dry-run\fP[=false]
	dry run writing components

.PP
\fB-f\fP, \fB--force-fetch\fP[=false]
	force refetching repos regardless of cache

.PP
\fB--git-cmd\fP="git"
	git cmd

.PP
\fB--git-cmd-quiet\fP[=false]
	quiet git cmd output

.PP
\fB--git-dir\fP=".git"
	git repo dir (.git)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for component

.PP
\fB-i\fP, \fB--input\fP=""
	main component definition

.PP
\fB--jsonnet-stdlib\fP="anvil:std"
	jsonnet std lib import name

.PP
\fB-m\fP, \fB--no-network\fP[=false]
	error if the network is required

.PP
\fB-o\fP, \fB--output\fP="anvil_out"
	generated component output directory

.PP
\fB--repo-sum\fP="anvil.sum.json"
	checksum file


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/anvil/anvil.json)

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBanvil(1)\fP
