.nh
.TH "anvil" "1" "Apr 2023" "" ""

.SH NAME
.PP
anvil-secret - Uploads secret configs


.SH SYNOPSIS
.PP
\fBanvil secret [flags]\fP


.SH DESCRIPTION
.PP
Uploads secret configs


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for secret


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/anvil/anvil.yaml)

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBanvil(1)\fP, \fBanvil-secret-vault(1)\fP
