.nh
.TH "anvil" "1" "Oct 2021" "" ""

.SH NAME
.PP
anvil\-secret \- Uploads secret configs


.SH SYNOPSIS
.PP
\fBanvil secret [flags]\fP


.SH DESCRIPTION
.PP
Uploads secret configs


.SH OPTIONS
.PP
\fB\-n\fP, \fB\-\-dry\-run\fP[=false]
	dry run

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for secret

.PP
\fB\-\-vault\-policies\fP=""
	vault secret policies

.PP
\fB\-\-vault\-roles\fP=""
	vault secret roles

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
	verbose output


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.anvil.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output


.SH SEE ALSO
.PP
\fBanvil(1)\fP
