.nh
.TH "anvil" "1" "Mar 2024" "" ""

.SH NAME
.PP
anvil-doc-man - generate man page documentation for anvil


.SH SYNOPSIS
.PP
\fBanvil doc man [flags]\fP


.SH DESCRIPTION
.PP
generate man page documentation for anvil


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for man


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/anvil/anvil.json)

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBanvil-doc(1)\fP
